// Module user
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

// Module guides
export const GUIDES_REQUEST = 'GUIDES_REQUEST'
export const GUIDES_SUCCESS = 'GUIDES_SUCCESS'
export const GUIDES_FAILURE = 'GUIDES_FAILURE'

// Module guide info
export const GUIDE_INFO_REQUEST = 'GUIDE_INFO_REQUEST'
export const GUIDE_INFO_SUCCESS = 'GUIDE_INFO_SUCCESS'
export const GUIDE_INFO_FAILURE = 'GUIDE_INFO_FAILURE'

// Add photo
export const GUIDE_PHOTO_REQUEST = 'GUIDE_PHOTO_REQUEST'
export const GUIDE_PHOTO_SUCCESS = 'GUIDE_PHOTO_SUCCESS'
export const GUIDE_PHOTO_FAILURE = 'GUIDE_PHOTO_FAILURE'

export const GUIDE_PHOTO_ADD_REQUEST = 'GUIDE_PHOTO_ADD_REQUEST'
export const GUIDE_PHOTO_ADD_SUCCESS = 'GUIDE_PHOTO_ADD_SUCCESS'
export const GUIDE_PHOTO_ADD_FAILURE = 'GUIDE_PHOTO_ADD_FAILURE'

export const GUIDE_PHOTO_REMOVE_SUCCESS = 'GUIDE_PHOTO_REMOVE_SUCCESS'
